# vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab:

name: Download addresses
on:
  workflow_dispatch:
  schedule:
    - cron: "5 4 13 * *"  # about ‘monthly’

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  download-addresses:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          cache: pip
    
      - run: sudo apt update && sudo apt install gdal-bin

      - run: pip install -r requirements.txt

      - run: |
          ./download-addresses.py
          ls -alhtr
          mkdir -p output
          mv austrian-addresses{,-voronoi}.gpkg.zip output/

      - uses: actions/upload-artifact@v4
        with:
          name: addresses
          path: output/

      - uses: actions/upload-pages-artifact@v3
        with:
          path: output/

  deploy-pages:
      runs-on: ubuntu-latest
      needs: download-addresses
      environment: 
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      permissions:
        id-token: write
        pages: write
      steps:
        - uses: actions/deploy-pages@v4
          id: deployment
